---
version: "3.8"
services:
  # mongo_db:
  #   container_name: ${COMPOSE_PROJECT_NAME:-green_atom}-mongo
  #   image: mongo:latest
  #   restart: unless-stopped
  #   volumes:
  #     - mongo_data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27017:27017/tcp

  db:
    container_name: ${COMPOSE_PROJECT_NAME:-green_atom}-pgsql
    image: postgres:15
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-green_atom}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-green_atom}
      POSTGRES_DB: ${DB_DATABASE:-users}
    ports:
      - 15432:5432/tcp

  rack:
    container_name: ${COMPOSE_PROJECT_NAME:-green_atom}-rack
    build: .
    command: bundle exec rackup --host 0.0.0.0 -p 9292 config.ru
    depends_on:
      # - mongo_db
      - db
    ports:
      - 9292:9292/tcp
    environment:
      DOCKER_ENV: true

volumes:
  # mongo_data:
  pg_data:
